// By samillee, Truslab Inc.
// Auto generated by Entity developer, updated at 2018-11-14

// Package file contains structures for Elasticsearch model in general
package file

import (
  "fmt"
  "time"
)

// ProcessType for elasticsearch
type ProcessType struct {
  Name *string   `json:"name,omitempty" maxLength:"100"`        
  ProcessName *string   `json:"ProcessName,omitempty"`        
  Processid *int32 `json:"processid,omitempty"`
  Caption *string `json:"caption,omitempty"`
  Description *string `json:"description,omitempty"`
  CommandLine *string `json:"commandline,omitempty"`
  ExecutablePath *string `json:"executablepath,omitempty"`
}

// DebugInfo ...
func (t ProcessType) DebugInfo() string {
  return fmt.Sprintf("%s at %v", "ProcessType", time.Now())
}


// GetWmiClass ...
func (t ProcessType) GetWmiClass() string {
  return "Win32_Process"
}

// GetWmiFields ...
func (t ProcessType) GetWmiFields() string {
  return "name,ProcessName,processid,caption,description,commandline,executablepath"
}

// GetPsWmiClassQuery ...
func (t ProcessType) GetPsWmiClassQuery() (string, string) {
  var q = `PowerShell /command "Get-WmiObject -class %s | Select-Object %s | convertto-json | out-file %s -encoding UTF8"`

  tv := time.Now()
  var fn = fmt.Sprintf("%s_%s.json", t.GetWmiClass(), tv.Format("2006-01-02T15-04-05"))
  
  return fmt.Sprintf(q, t.GetWmiClass(), t.GetWmiFields(), fn), fn
}

// GetPsWqlQuery ...
func (t ProcessType) GetPsWqlQuery() (string, string) {
  var q = `PowerShell /command "Get-WmiObject -query '%s' | Select-Object %s | convertto-json | out-file %s -encoding UTF8"`

  tv := time.Now()
  var fn = fmt.Sprintf("%s_%s.json", t.GetWmiClass(), tv.Format("2006-01-02T15-04-05"))
  
  return fmt.Sprintf(q, t.GetWql(), t.GetWmiFields(), fn), fn
}

// GetPsQuery ...
func (t ProcessType) GetPsQuery() (string, string) {
    return t.GetPsWmiClassQuery()
}

// GetWql ...
func (t ProcessType) GetWql() string {
  var q = `select %s from %s`
  
  return fmt.Sprintf(q, t.GetWmiFields(), t.GetWmiClass())
}
